
apiVersion: build.openshift.io/v1
kind: "BuildConfig"
metadata:
  name: blog-from-image-config-grupo-07
  namespace: fiap-aso6-grupo07
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'blog-django-py-git-grupo-07:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8-ubi7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-katacoda/blog-django-py.git'
    contextDir: /
  triggers:
    - type: ConfigChange
  runPolicy: Serial
    