apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpascale
  namespace: fiap-aso6-grupo07
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-from-image
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
